In [49]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [80]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Customer_datasets - Customer_datasets.csv")
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2025,1131,Customer_1131,74,46818.31,2018-08-09,Marketing,46.8,user1130@outlook.com,Phoenix,Other,FALSE
2026,1295,Customer_1295,72,64255.45,2017-08-23,Support,Excellent,user1294@outlook.com,San Jose,Male,FALSE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

1. How many missing values are there in each column? Which column has the highest
number of missing values?

In [62]:
missing_value=df.isnull().sum()
print(missing_value)
missing_value.idxmax()

Customer_ID            0
Name                 145
Age                   84
Salary                97
Join_Date            254
Department            51
Performance_Score     39
Email                 49
City                  43
Gender                34
Is_Active             25
dtype: int64

'Join_Date'

2. What percentage of rows have at least one missing value?

In [63]:
missing_values=df.isnull().any(axis=1).sum()
total=len(df)
per=(missing_values/total)*100
per

np.float64(34.87684729064039)

3. Drop all rows that have more than 3 missing values. How many rows remain?

In [64]:
missing_values=df.isnull().sum(axis=1)
df.drop(df[missing_values > 3].index)
len(df)

2030

4. How many exact duplicate rows are present in the dataset?

In [65]:
duplicate_rows=df.duplicated().sum()
print(duplicate_rows)

30

5. How many duplicate Customer_IDs are there? Keep only the first occurrence of each
Customer_ID.

In [66]:
df.duplicated().sum()

np.int64(30)

In [67]:
df["Customer_ID"].duplicated().sum()
df.drop_duplicates(subset="Customer_ID", keep="first", inplace=True)
df

,Customer_ID,Name,Age,Salary,Join_Date,Department,Performance_Score,Email,City,Gender,Is_Active
0,1357,Customer_1357,27,29664.12,2022-06-14,HR,69.1,user1356@outlook.com,Houston,Male,FALSE
1,985,Customer_985,27,47373.17,NaN,Marketing,1.9,user984@yahoo.com,Dallas,Female,FALSE
2,1828,Customer_860,62,63380.36,20170530,Operations,78.2,user859@gmail.com,NaN,Male,NaN
3,1985,Customer_1985,thirty,56746.57,2016-12-19 00:00:00,IT,85.8,user1984@company.com,New York,Male,TRUE
4,1294,Customer_1294,41,61654.21,2019-03-12,Finance,82.5,user1293@gmail.com,NEW YORK,Other,TRUE
...,...,...,...,...,...,...,...,...,...,...,...
2023,1725,Customer_1725,69,41999.16,2019-11-01,Operations,45.7,user1724@outlook.com,Chicago,Other,FALSE
2024,1096,Customer_1096,74,43331.22,2016-09-10 00:00:00,Finance,92.2,user1095@gmail.com,San Antonio,Male,TRUE
2027,861,Customer_861,21,NaN,2019-10-28,Finance,43.7,user860@gmail.com,Los Angeles,Other,TRUE
2028,1460,Customer_1460,69,46179.42,2020-01-06,IT,17.5,user1459@outlook.com,Los Angeles,Female,FALSE
2029,1127,Customer_1127,65,58869.43,2020-01-17,Finance,47.4,user1126@outlook.com,San Jose,Male,FALSE

In [68]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'Salary', 'Join_Date', 'Department',
       'Performance_Score', 'Email', 'City', 'Gender', 'Is_Active'],
      dtype='object')

6. Convert the Age column to numeric. How many values could not be converted
(became NaN)?

In [69]:
df['Age']=pd.to_numeric(df['Age'],errors='coerce')
df=df['Age'].isna().sum()
print(df)

116

In [73]:
print(df.columns)

Index(['Customer_ID', 'Name', 'Age', 'Salary', 'Join_Date', 'Department',
       'Performance_Score', 'Email', 'City', 'Gender', 'Is_Active'],
      dtype='object')

7. After converting Age to numeric, identify and remove outliers using the IQR method.
How many outliers were removed?

In [74]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Age'] < lower) | (df['Age'] > upper)]

print("Outliers:", len(outliers))

df.drop(outliers.index, inplace=True)

Outliers: 11

8. Replace remaining missing values in Age with the median age.

In [75]:
median_age=df['Age'].median()
df['Age']=df['Age'].fillna(median_age)
print(median_age)
print(df['Age'].isna().sum())

49.0
0

9. Clean the Salary column: remove currency symbols ($), commas, and convert
everything possible to numeric. How many values remained non-numeric?

In [76]:
df["Salary"] = df["Salary"].astype(str)
df["Salary"] = df["Salary"].str.replace("$", "")
df["Salary"] = df["Salary"].str.replace(",", "")
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Salary"].isnull().sum()

np.int64(121)

10. After cleaning, find the mean and median salary. Which one is more affected by
outliers?

In [77]:
mean=df["Salary"].mean()
median=df["Salary"].median()
print(mean)
print(median)

59223.27233930453
55562.315

11. Convert the Join_Date column to proper datetime format. How many dates failed to
parse?

In [78]:
df["Join_Date"] = pd.to_numeric(df["Join_Date"], errors="coerce")
failed_dates=df['Join_Date'].isna().sum()
print(failed_dates)

1962

12. Extract the year from the cleaned Join_Date. What is the most common joining year?

In [82]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")
df["Year"] = df["Join_Date"].dt.year
df["Year"].mode()[0]

np.float64(2019.0)

13. Standardize the Department column (fix casing, trim spaces, fix common typos like
“Sale” → “Sales”, “Financ” → “Finance”, etc.). How many unique departments remain
after cleaning?

In [83]:
df["Department"] = df["Department"].str.strip().str.title()
df["Department"] = df["Department"].replace({
    "Sale": "Sales",
    "Financ": "Finance"})
df["Department"].nunique()

11

14. Clean the City column (standardize names, fix “Los Angles” → “Los Angeles”, “NY” →
“New York”, “Philly” → “Philadelphia”, etc.). List the final unique cities.

In [84]:
df["City"] = df["City"].str.strip().str.title()
df["City"] = df["City"].replace({
    "Los Angles": "Los Angeles",
    "Ny": "New York",
    "Philly": "Philadelphia"
})
df["City"].unique()

array(['Houston', 'Dallas', nan, 'New York', 'San Antonio', 'Los Angeles',
       'San Diego', 'Chicago', 'Houston Tx', 'San Jose', 'Philadelphia',
       'Phoenix', 'Unknown'], dtype=object)

15. Standardize the Gender column so it only contains “Male”, “Female”, and “Other”.
How many records were changed?

In [85]:
original = df['Gender'].copy()
df['Gender'] = df['Gender'].str.strip().str.title()
df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'F': 'Female',
    'Man': 'Male',
    'Woman': 'Female'
})
changed = (original != df['Gender']).sum()
changed

np.int64(62)

16. Convert Performance_Score to numeric. Replace non-numeric values with NaN, then
fill missing scores with the mean.

In [86]:
df['Performance_Score'] = pd.to_numeric(df['Performance_Score'], errors='coerce')
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].mean())
df['Performance_Score']

0       69.10000
1        1.90000
2       78.20000
3       85.80000
4       82.50000
          ...
2025    46.80000
2026    51.67763
2027    43.70000
2028    17.50000
2029    47.40000
Name: Performance_Score, Length: 2030, dtype: float64

17. Clean the Is_Active column so it becomes a proper boolean (True/False). Map values
like “Yes”, “Y”, “1”, “Active”, “true” → True and “No”, “N”, “0”, “Inactive”, “false” →
False.

In [87]:
df['Is_Active'] = df['Is_Active'].astype(str).str.strip().str.lower()
df['Is_Active'] = df['Is_Active'].map({
    'yes': True,
    'y': True,
    '1': True,
    'active': True,
    'true': True,
    
    'no': False,
    'n': False,
    '0': False,
    'inactive': False,
    'false': False
})
df['Is_Active']
df['Is_Active'].unique()
df['Is_Active'].value_counts()

Is_Active
False    1031
True      974
Name: count, dtype: int64

19. Clean the Name column: replace empty strings, “N/A”, and “Unknown” with NaN.
How many names are still missing after this step?

In [88]:
import numpy as np
df['Name'] = df['Name'].replace(['', 'N/A', 'Unknown'], np.nan)
df['Name'].isna().sum()

np.int64(155)