In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 1 – Complete Data Cleaning
Your manager gives you a messy dataset.
Perform all of the following:
• Load the dataset.
• Display dataset information.
• Find missing values.
• Remove duplicate rows.
• Fill missing values:
o Age → median
o Balance → mean
• Rename:
o Target → CustomerStatus
o AnnualIncome → Income
• Display the first 15 rows.

In [4]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df.info()
df.isnull().sum()
df=df.drop_duplicates()
df['Age']=df['Age'].fillna(df['Age'].median())
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
df=df.rename(columns={
    "Target":"CustomerStatus",
    "AnnualIncome":"Income"})
df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

Challenge 2 – Banking Report
The bank wants a numeric report.
Tasks
• Select only numeric columns.
• Display summary statistics.
• Convert Age and CreditScore to float.
• Display information again.

In [7]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [8]:
df=df.select_dtypes(include=["number"])
df.head()
df.describe()
df['Age']=df['Age'].astype(float)
df['CreditScore']=df['CreditScore'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
dtypes: float64(4), int64(3)
memory usage: 55.9 KB

Challenge 3 – Duplicate Investigation
Find duplicate customers.
Then
• Count duplicate rows.
• Remove duplicates.
• Print information before and after removing duplicates.
• Show the last 20 rows.

In [14]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [15]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.info()
df.tail(20)

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
980,10981,41.0,199633.0,8498,847,173390.59,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541,59484.58,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334,NaN,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732,175352.25,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730,120423.19,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488,126031.27,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621,115161.87,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720,158528.46,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884,44897.43,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773,39653.24,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452,17812.25,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764,165451.49,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594,149288.61,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493,83666.20,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

Challenge 4 – HR Department
HR wants better column names.
Rename
CustomerID → Employee_ID
Age → EmployeeAge
Gender → EmployeeGender
AnnualIncome → Salary
Target → PromotionStatus
Then
• Add prefix
HR_
to every column.
Display 10 random records.

In [17]:
df=df.rename(columns={
    "CustomerID":"Employee_ID",
    "Age":"EmployeeAge",
    "Gender":"EmployeeGender",
    "AnnualIncome":"Salary",
    "Target":"PromotionStatus"})
df=df.add_prefix("HR_")
df.sample(10)

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
784,10785,33.0,64898.0,5168,618,122652.58,5,Germany,Female,Retail,Stay
813,10814,21.0,110058.0,35563,311,93773.76,8,Canada,Other,SME,Churn
447,10448,69.0,54207.0,22831,481,183756.16,5,India,Male,Retail,Churn
507,10508,62.0,110269.0,20953,432,20541.64,8,Germany,Female,Retail,Churn
853,10854,39.0,36573.0,8413,580,28247.36,6,USA,Other,Corporate,Stay
767,10768,53.0,104914.0,901,416,137167.16,5,Canada,NaN,SME,Churn
686,10687,19.0,182459.0,24360,544,64138.82,1,France,Other,Corporate,Churn
438,10439,21.0,42995.0,18835,692,27447.20,3,France,Other,Retail,Stay
136,10137,34.0,139756.0,20299,503,199874.71,7,India,Male,NaN,Stay
810,10811,20.0,168937.0,32171,677,22632.87,7,France,Male,Retail,Stay

In [19]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 5 – Finance Cleaning
Finance department reports missing values.
Tasks
Fill
AnnualIncome → Median
Balance → Mean
Age → Median
Then
Generate descriptive statistics.

In [20]:
df['AnnualIncome']=df['AnnualIncome'].fillna(df['AnnualIncome'].median())
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
df['Age']=df['Age'].fillna(df['Age'].median())
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,10501.599020,44.237255,112498.242157,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.136428,50925.015723,14219.393105,176.560690,54382.357541,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,31.000000,69223.000000,13134.750000,440.750000,52145.757500,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,97523.535666,5.000000
75%,10752.250000,57.000000,155570.750000,37956.000000,757.250000,142086.700000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

Challenge 6 – Data Type Audit
The company says
Age and AnnualIncome are stored incorrectly.
Tasks
Convert
Age → int
AnnualIncome → float
Balance → float
Target → string
Print information.

In [21]:
df['Age']=df['Age'].astype(int)
df['AnnualIncome']=df['AnnualIncome'].astype(float)
df['Balance']=df['Balance'].astype(float)
df['Target']=df['Target'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   int64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 87.8+ KB

Challenge 7 – Customer Analytics
Create a new DataFrame that
• removes Segment
• removes Geography
• removes duplicate rows
Display
• first 10 rows
• dataset information
• statistical summary

In [23]:
df=df.drop(columns=["Segment","Geography"])
df=df.drop_duplicates()
df.head(10)
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    object
 8   Target        1000 non-null   object
dtypes: float64(2), int64(5), object(2)
memory usage: 78.1+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112453.288000,25285.558000,603.088000,97555.864273,5.241000
std,288.819436,15.130834,51081.479931,14211.735656,176.605486,54430.062511,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112358.000000,24901.000000,606.500000,97523.535666,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [3]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [15]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [16]:
df.columns

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment', 'Target'],
      dtype='object')

Challenge 8 – ML Dataset Preparation
Prepare a machine learning dataset.
Perform
• Remove duplicates
• Remove CustomerID
• Remove Segment
• Fill missing values
• Rename Target to Output
Finally
Display
head()
info()
describe()
value_counts(Output)

In [18]:
df.drop_duplicates()
df.drop(columns=["Segment","CustomerID"])
df["Age"]=df["Age"].fillna(df["Age"].median())
df['Balance']=df['Balance'].fillna(df['Balance'].mean())
df['AnnualIncome']=df['AnnualIncome'].fillna(df['AnnualIncome'].mean())
df.rename(columns={"Target":"Output"},inplace=True)
df.head()
df.info()
df.describe()
df['Output'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Output
Churn    515
Stay     505
Name: count, dtype: int64

Challenge 9 – Column Transformation
Create these new columns
NetWorth = Balance + AnnualIncome
AgeAfterRetirement = Age + 20
DoubleCreditScore = CreditScore * 2
IncomePerMonth = AnnualIncome / 12
Then
Display first 15 rows.

In [20]:
df['NetWorth']=df['Balance']+df['AnnualIncome']
df['AgeAfterRetirement']=df['Age']+20
df['DoubleCreditScore']=df['CreditScore']*2
df['IncomePerMonth']=df['AnnualIncome']/12
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Output,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay,146707.535666,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn,169320.540000,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay,170159.920000,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn,232553.880000,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn,184221.460000,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay,138635.620000,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn,220598.720000,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay,269157.730000,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay,104539.410000,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn,286507.980000,42.0,950,14973.333333
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay,231695.030000,64.0,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn,115931.720000,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay,179444.320000,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay,174562.770000,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn,304725.430000,46.0,786,12797.416667

Challenge 10 – Company Report
Display
• first five rows
• last five rows
• ten random rows
• dataset information
• descriptive statistics
Finally rename
Target → Customer_Status

In [25]:
print(df.head(5))
print(df.tail(5))
print(df.sample(10))
print(df.info())
print(df.describe())
df.rename(columns={"Target":"Customer_Status"},inplace=True)

   CustomerID   Age  AnnualIncome  Spending  CreditScore        Balance  \
0       10001  58.0       49184.0      2139          581   97523.535666
1       10002  65.0      162964.0      6197          732    6356.540000
2       10003  56.0       26956.0     37281          503  143203.920000
3       10004  55.0       92926.0       925          463  139627.880000
4       10005  66.0      108236.0      7198          394   75985.460000

   Tenure Geography Gender    Segment Output       NetWorth  \
0       2    France   Male        SME   Stay  146707.535666
1       1       USA   Male        SME  Churn  169320.540000
2       8    Canada   Male  Corporate   Stay  170159.920000
3       5       NaN   Male     Retail  Churn  232553.880000
4       5        UK  Other  Corporate  Churn  184221.460000

   AgeAfterRetirement  DoubleCreditScore  IncomePerMonth
0                78.0               1162     4098.666667
1                85.0               1464    13580.333333
2                76.0               1006     2246.333333
3                75.0                926     7743.833333
4                86.0                788     9019.666667
      CustomerID   Age   AnnualIncome  Spending  CreditScore        Balance  \
1015       10450  43.0  173620.000000      7121          644   60353.030000
1016       10753  25.0   54490.000000     13794          303  124512.070000
1017       10810  49.0   82062.000000     47170          813   53850.090000
1018       10267  38.0  112505.928645     10424          722  138100.050000
1019       10059  62.0   97504.000000     36833          430   97523.535666

      Tenure Geography  Gender    Segment Output       NetWorth  \
1015       2       USA   Other  Corporate   Stay  233973.030000
1016       4     India     NaN  Corporate  Churn  179002.070000
1017       8   Germany  Female     Retail   Stay  135912.090000
1018       6   Germany   Other  Corporate   Stay  250605.978645
1019      10    Canada   Other        NaN  Churn  195027.535666

      AgeAfterRetirement  DoubleCreditScore  IncomePerMonth
1015                63.0               1288    14468.333333
1016                45.0                606     4540.833333
1017                69.0               1626     6838.500000
1018                58.0               1444     9375.494054
1019                82.0                860     8125.333333
     CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
75        10076  39.0      195341.0     45008          714  144836.28       7
442       10443  32.0       61844.0      7062          553  131372.88       4
667       10668  26.0       95915.0      7732          766  123545.88       4
537       10538  70.0       34227.0     15109          765   66394.53       9
132       10133  27.0       84014.0     35310          721  113185.61       2
156       10157  18.0      113911.0     16093          631    3156.22       4
494       10495  43.0      193154.0     21444          443  144256.64      10
357       10358  32.0      136858.0     25018          700   92612.64      10
656       10657  24.0       88800.0     41007          459   16862.25       6
373       10374  49.0       63844.0      5917          878    6172.14       3

    Geography  Gender    Segment Output   NetWorth  AgeAfterRetirement  \
75        USA   Other        SME   Stay  340177.28                59.0
442   Germany   Other     Retail   Stay  193216.88                52.0
667    France   Other  Corporate   Stay  219460.88                46.0
537   Germany  Female        SME   Stay  100621.53                90.0
132       USA    Male        NaN   Stay  197199.61                47.0
156     India     NaN        SME  Churn  117067.22                38.0
494    Canada  Female        NaN  Churn  337410.64                63.0
357   Germany     NaN        SME   Stay  229470.64                52.0
656        UK    Male     Retail  Churn  105662.25                44.0
373        UK    Male  Corporate  Churn   70016.14                69.0

     DoubleCreditScore  IncomePerMonth
75                1428    16278.416667
442               1106     5153.666667
667               1532     7992.916667
537               1530     2852.250000
132               1442     7001.166667
156               1262     9492.583333
494                886    16096.166667
357               1400    11404.833333
656                918     7400.000000
373               1756     5320.333333
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   float64
 2   AnnualIncome        1020 non-null   float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Output              1020 non-null   object
 11  NetWorth            1020 non-null   float64
 12  AgeAfterRetirement  1020 non-null   float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      1020 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB
None
         CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  1020.000000    1020.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112505.928645  25232.615686   602.659804
std      288.022115    15.136428   50925.005129  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   69223.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112505.928645  24798.000000   607.000000
75%    10752.250000    57.000000  155570.750000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure       NetWorth  AgeAfterRetirement  \
count    1020.000000  1020.000000    1020.000000         1020.000000
mean    97523.535666     5.261765  210029.464311           64.237255
std     54382.357541     3.185330   72924.876967           15.136428
min       547.600000     0.000000   33432.390000           38.000000
25%     52145.757500     2.000000  156965.307500           51.000000
50%     97523.535666     5.000000  210040.067155           64.000000
75%    142086.700000     8.000000  262725.185000           77.000000
max    199885.880000    10.000000  390628.400000           90.000000

       DoubleCreditScore  IncomePerMonth
count        1020.000000     1020.000000
mean         1205.319608     9375.494054
std           353.121379     4243.750427
min           600.000000     1685.583333
25%           881.500000     5768.583333
50%          1214.000000     9375.494054
75%          1514.500000    12964.229167
max          1800.000000    16663.916667

Challenge 11 – Missing Value Report
Create a report showing
• Total missing values
• Numerical columns
• Mean of Balance
• Median of Age
• Fill missing values
• Display information again

In [26]:
df.isnull().sum()
df.select_dtypes(include="number").columns
df['Balance']=df['Balance'].mean()
df["Age"]=df["Age"].median()
df["Age"].fillna(df["Age"],inplace=True)
df['Balance'].fillna(df['Balance'],inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          1020 non-null   int64
 1   Age                 1020 non-null   float64
 2   AnnualIncome        1020 non-null   float64
 3   Spending            1020 non-null   int64
 4   CreditScore         1020 non-null   int64
 5   Balance             1020 non-null   float64
 6   Tenure              1020 non-null   int64
 7   Geography           969 non-null    object
 8   Gender              968 non-null    object
 9   Segment             969 non-null    object
 10  Output              1020 non-null   object
 11  NetWorth            1020 non-null   float64
 12  AgeAfterRetirement  1020 non-null   float64
 13  DoubleCreditScore   1020 non-null   int64
 14  IncomePerMonth      1020 non-null   float64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB

In [27]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 12 – Customer Classification
Count
Stay

Churn
Then
Rename
Target → Customer_Class
Convert it into string.

In [28]:
df["Target"].value_counts()
df.rename(columns={"Target":"Customer_Class"},inplace=True)
df['Customer_Class']=df['Customer_Class'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             970 non-null    float64
 2   AnnualIncome    967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   int64
 5   Balance         969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  Customer_Class  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [29]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [ ]:
Challenge 13 – Sales Department
Rename
Balance → AccountBalance
AnnualIncome → Salary
CreditScore → Score
Add prefix
Sales_
Then
Display
sample(20)

In [30]:
df.rename(columns={"Balance":" AccountBalance"},inplace=True)
df.rename(columns={"AnnualIncome":"Salary"},inplace=True)
df.rename(columns={"CreditScore":"Score"},inplace=True)
df=df.add_prefix("Sales_")
df.sample(20)

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_ AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
219,10220,66.0,107167.0,9243,345,70459.81,5,France,Male,SME,Churn
608,10609,20.0,159311.0,33486,420,18637.99,10,USA,Other,SME,Churn
443,10444,66.0,77517.0,38228,697,70960.93,2,USA,Male,SME,Stay
833,10834,67.0,131931.0,45865,631,51467.32,1,UK,Male,Corporate,Churn
985,10986,62.0,27169.0,3914,488,126031.27,10,USA,Male,Corporate,Churn
482,10483,50.0,125744.0,9389,836,175866.52,0,USA,NaN,Retail,Churn
318,10319,54.0,84416.0,33222,863,130921.59,10,UK,Female,Corporate,Stay
958,10959,69.0,148020.0,7057,510,67193.49,8,France,Female,Retail,Stay
653,10654,46.0,115201.0,49514,833,193105.21,6,USA,Male,Retail,Stay
889,10890,58.0,NaN,19713,726,193914.92,8,USA,Female,Corporate,Stay
430,10431,33.0,113255.0,26468,825,9790.12,4,UK,Male,Retail,Churn
400,10401,NaN,179102.0,33892,493,149568.73,4,France,Male,Retail,Churn
214,10215,58.0,155102.0,38186,547,143708.87,4,Canada,Male,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
476,10477,59.0,147293.0,37988,784,7493.13,4,Canada,Male,SME,Churn
647,10648,65.0,107728.0,17524,669,72061.32,8,UK,Female,Retail,Stay
454,10455,28.0,186772.0,6314,643,89325.99,4,USA,Male,SME,Stay
173,10174,51.0,76395.0,25154,729,90729.16,2,UK,Female,SME,Stay
399,10400,23.0,85055.0,36767,591,155793.93,0,NaN,Female,Retail,Churn
467,10468,66.0,194972.0,6837,387,133628.23,8,Canada,Other,Retail,Churn

In [31]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 14 – Interview Challenge
Without creating another DataFrame,
perform
• remove duplicates
• rename Target
• fill missing values
• convert Balance to float
• display summary

In [32]:
df.drop_duplicates()
df.rename(columns={"Target":"Customer_Status"},inplace=True)
df["Age"].fillna(df["Age"],inplace=True)
df['Balance'].fillna(df['Balance'],inplace=True)
df['Balance']=df['Balance'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1020 non-null   int64
 1   Age              970 non-null    float64
 2   AnnualIncome     967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   Geography        969 non-null    object
 8   Gender           968 non-null    object
 9   Segment          969 non-null    object
 10  Customer_Status  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Challenge 15 – Data Engineer Task
Load the dataset.
Create another DataFrame containing only numeric columns.
Drop
CustomerID
Target
Display summary.

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [6]:
df = df.select_dtypes(include="number")
print(df.describe())
df.drop(columns=["CustomerID", "Target"], inplace=True,errors="ignore")

       Company_Customer_ID  Company_Age  Company_Income  Company_Spending  \
count          1000.000000  1000.000000     1000.000000       1000.000000
mean          10500.500000    44.202000   112452.763000      25285.558000
std             288.819436    15.130834    51081.480963      14211.735656
min           10001.000000    18.000000    20227.000000        537.000000
25%           10250.750000    31.000000    68437.250000      13213.000000
50%           10500.500000    44.000000   112347.500000      24901.000000
75%           10750.250000    57.000000   155570.750000      37960.250000
max           11000.000000    70.000000   199967.000000      49995.000000

       Company_Credit_Score  Company_Balance  Company_Tenure
count           1000.000000      1000.000000     1000.000000
mean             603.088000     97557.565779        5.241000
std              176.605486     54430.062006        3.179155
min              300.000000       547.600000        0.000000
25%              441.000000     52074.240000        2.000000
50%              606.500000     97557.565779        5.000000
75%              758.250000    142297.910000        8.000000
max              900.000000    199885.880000       10.000000

Challenge 16 – Mixed Cleaning
Perform
drop_duplicates()
fillna()
astype()
rename()
head()
info()
using only one DataFrame variable.

In [4]:
df.drop_duplicates(inplace=True)
df["Age"].fillna(df["Age"],inplace=True)
df['Balance'].fillna(df['Balance'],inplace=True)
df['Balance']=df['Balance'].astype(float)
df.rename(columns={"Target":"Customer_Status"},inplace=True)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 62.5 KB

In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 17 – Real Company Dataset
Manager asks
Remove duplicate records

Fill missing values
Rename all business columns
Add company prefix
Display summary
Display target counts

In [2]:
df.drop_duplicates(inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
}, inplace=True)

df.columns = "Company_" + df.columns
print(df.describe())
print(df["Company_Customer_Status"].value_counts())

       Company_Customer_ID  Company_Age  Company_Income  Company_Spending  \
count          1000.000000  1000.000000     1000.000000       1000.000000
mean          10500.500000    44.202000   112452.763000      25285.558000
std             288.819436    15.130834    51081.480963      14211.735656
min           10001.000000    18.000000    20227.000000        537.000000
25%           10250.750000    31.000000    68437.250000      13213.000000
50%           10500.500000    44.000000   112347.500000      24901.000000
75%           10750.250000    57.000000   155570.750000      37960.250000
max           11000.000000    70.000000   199967.000000      49995.000000

       Company_Credit_Score  Company_Balance  Company_Tenure
count           1000.000000      1000.000000     1000.000000
mean             603.088000     97557.565779        5.241000
std              176.605486     54430.062006        3.179155
min              300.000000       547.600000        0.000000
25%              441.000000     52074.240000        2.000000
50%              606.500000     97557.565779        5.000000
75%              758.250000    142297.910000        8.000000
max              900.000000    199885.880000       10.000000
Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

Challenge 18 – Customer Summary
Generate
Mean Balance
Median Balance
Mean Age
Median AnnualIncome

Then
fill missing values using these statistics.

In [5]:
mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
mean_age = df["Age"].mean()
median_income = df["AnnualIncome"].median()
print(mean_balance)
print(median_balance)
print(mean_age)
print(median_income)
df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)
print(df.isnull().sum())

97557.56577894738
95174.625
44.21263157894737
112347.5
CustomerID      0
Age             0
AnnualIncome    0
Spending        0
CreditScore     0
Balance         0
Tenure          0
dtype: int64

Challenge 19 – Transformation Challenge
Create
Income_in_Lakhs
Balance_in_Lakhs

SeniorCitizen
HighCreditScore
where
SeniorCitizen = Age + 0
HighCreditScore = CreditScore * 1
(No conditional statements.)

In [6]:
df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000
df["Balance_in_Lakhs"] = df["Balance"] / 100000
df["SeniorCitizen"] = df["Age"] + 0
df["HighCreditScore"] = df["CreditScore"] * 1
df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,97557.565779,2,0.49184,0.975576,58.0,581
1,10002,65.0,162964.0,6197,732,6356.540000,1,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.920000,8,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.880000,5,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.460000,5,1.08236,0.759855,66.0,394
5,10006,69.0,31390.0,48323,770,107245.620000,6,0.31390,1.072456,69.0,770
6,10007,58.0,182141.0,24200,891,38457.720000,1,1.82141,0.384577,58.0,891
7,10008,67.0,95861.0,5729,538,173296.730000,6,0.95861,1.732967,67.0,538
8,10009,41.0,62638.0,24760,663,41901.410000,4,0.62638,0.419014,41.0,663
9,10010,22.0,179680.0,42113,475,106827.980000,3,1.79680,1.068280,22.0,475

In [9]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Task_dataset - Task_dataset.csv")
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

Challenge 20 – Final Interview Project
Your manager gives you a dirty customer dataset.
Prepare the final dataset.
Requirements
Load dataset
Check information
Find missing values
Remove duplicates
Rename
CustomerID
AnnualIncome
CreditScore
Target

Convert
Age
AnnualIncome
Balance

Fill missing values
Remove
Segment
CustomerID
Create new columns
TotalMoney = Balance + AnnualIncome
AgeAfter5Years = Age + 5
MonthlyIncome = AnnualIncome / 12
CreditScoreDouble = CreditScore * 2Display
• Head
• Tail
• Sample
• Describe
• Target counts
• Final information

In [10]:
df.info()
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
}, inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)
df["Income"] = df["Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Income"] = df["Income"].fillna(df["Income"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.drop(columns=["Segment", "Customer_ID"], inplace=True)
df["TotalMoney"] = df["Balance"] + df["Income"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["Income"] / 12
df["CreditScoreDouble"] = df["Credit_Score"] * 2
print("First 5 Rows:")
print(df.head())
print("Last 5 Rows:")
print(df.tail())
print("Random Sample:")
print(df.sample(10))
print("Statistical Summary:")
print(df.describe())
print("Customer Status Counts:")
print(df["Customer_Status"].value_counts())
print("Final Dataset Information:")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
First 5 Rows:
   Age    Income  Spending  Credit_Score        Balance  Tenure Geography  \
0   58   49184.0      2139           581   97557.565779       2    France
1   65  162964.0      6197           732    6356.540000       1       USA
2   56   26956.0     37281           503  143203.920000       8    Canada
3   55   92926.0       925           463  139627.880000       5       NaN
4   66  108236.0      7198           394   75985.460000       5        UK

  Gender Customer_Status     TotalMoney  AgeAfter5Years  MonthlyIncome  \
0   Male            Stay  146741.565779              63    4098.666667
1   Male           Churn  169320.540000              70   13580.333333
2   Male            Stay  170159.920000              61    2246.333333
3   Male           Churn  232553.880000              60    7743.833333
4  Other           Churn  184221.460000              71    9019.666667

   CreditScoreDouble
0               1162
1               1464
2               1006
3                926
4                788
Last 5 Rows:
     Age    Income  Spending  Credit_Score    Balance  Tenure Geography  \
995   34   81731.0     40980           761  181465.65       5   Germany
996   47   42475.0      1176           780   26640.99       5    France
997   31  120531.0     46929           733  147220.82       4     India
998   21   33661.0     22314           540   94186.48       5       NaN
999   63   31930.0       851           559  100908.40       6        UK

     Gender Customer_Status  TotalMoney  AgeAfter5Years  MonthlyIncome  \
995   Other            Stay   263196.65              39    6810.916667
996  Female            Stay    69115.99              52    3539.583333
997    Male            Stay   267751.82              36   10044.250000
998   Other            Stay   127847.48              26    2805.083333
999  Female            Stay   132838.40              68    2660.833333

     CreditScoreDouble
995               1522
996               1560
997               1466
998               1080
999               1118
Random Sample:
     Age    Income  Spending  Credit_Score        Balance  Tenure Geography  \
674   67   44631.0     34653           513   94565.110000      10        UK
462   53  148699.0     10565           355   72165.780000       6     India
500   21  186303.0     38745           894  188860.200000       1    Canada
327   47  168111.0     16438           531   59994.930000       1    France
160   63  136277.0      5316           382   64422.360000       2     India
130   32   43692.0     28940           400  152073.940000       1    Canada
588   55  126203.0     39168           517  181260.720000       8        UK
312   53   76889.0     31917           513   97557.565779       5        UK
467   66  194972.0      6837           387  133628.230000       8    Canada
393   61  136671.0      1108           308  139119.420000       1    Canada

     Gender Customer_Status     TotalMoney  AgeAfter5Years  MonthlyIncome  \
674  Female            Stay  139196.110000              72    3719.250000
462  Female           Churn  220864.780000              58   12391.583333
500    Male           Churn  375163.200000              26   15525.250000
327   Other           Churn  228105.930000              52   14009.250000
160    Male           Churn  200699.360000              68   11356.416667
130    Male           Churn  195765.940000              37    3641.000000
588   Other            Stay  307463.720000              60   10516.916667
312    Male            Stay  174446.565779              58    6407.416667
467   Other           Churn  328600.230000              71   16247.666667
393   Other           Churn  275790.420000              66   11389.250000

     CreditScoreDouble
674               1026
462                710
500               1788
327               1062
160                764
130                800
588               1034
312               1026
467                774
393                616
Statistical Summary:
               Age         Income      Spending  Credit_Score        Balance  \
count  1000.000000    1000.000000   1000.000000   1000.000000    1000.000000
mean     44.202000  112452.763000  25285.558000    603.088000   97557.565779
std      15.130834   51081.480963  14211.735656    176.605486   54430.062006
min      18.000000   20227.000000    537.000000    300.000000     547.600000
25%      31.000000   68437.250000  13213.000000    441.000000   52074.240000
50%      44.000000  112347.500000  24901.000000    606.500000   97557.565779
75%      57.000000  155570.750000  37960.250000    758.250000  142297.910000
max      70.000000  199967.000000  49995.000000    900.000000  199885.880000

            Tenure     TotalMoney  AgeAfter5Years  MonthlyIncome  \
count  1000.000000    1000.000000     1000.000000    1000.000000
mean      5.241000  210010.328779       49.202000    9371.063583
std       3.179155   73150.769298       15.130834    4256.790080
min       0.000000   33432.390000       23.000000    1685.583333
25%       2.000000  156611.867500       36.000000    5703.104167
50%       5.000000  209916.897889       49.000000    9362.291667
75%       8.000000  263542.793945       62.000000   12964.229167
max      10.000000  390628.400000       75.000000   16663.916667

       CreditScoreDouble
count        1000.000000
mean         1206.176000
std           353.210972
min           600.000000
25%           882.000000
50%          1213.000000
75%          1516.500000
max          1800.000000
Customer Status Counts:
Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64
Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Income             1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    object
 7   Gender             950 non-null    object
 8   Customer_Status    1000 non-null   object
 9   TotalMoney         1000 non-null   float64
 10  AgeAfter5Years     1000 non-null   int64
 11  MonthlyIncome      1000 non-null   float64
 12  CreditScoreDouble  1000 non-null   int64
dtypes: float64(4), int64(6), object(3)
memory usage: 109.4+ KB