#Pandas Method Task

1. Load the dataset using the appropriate Pandas method and store it in a
variable named df.

In [3]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

2. Display the first 8 rows of the dataset.

In [4]:
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

3. Display the last 12 rows of the dataset.

In [5]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

4. Show 10 random rows from the dataset.

In [6]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3136,3137,15617877,Jessop,607,France,Male,44,0,0.00,2,1,1,81140.09,0
1496,1497,15799156,Okwuadigbo,569,Spain,Male,38,8,0.00,2,0,0,79618.79,0
6966,6967,15689661,Gorbunov,663,France,Male,22,6,0.00,2,0,1,131827.15,0
8060,8061,15776596,Ferri,730,Spain,Female,39,6,140094.59,1,1,0,172450.04,1
1075,1076,15762937,Chiganu,743,Germany,Female,32,6,140348.56,2,1,1,163254.39,0
4044,4045,15607142,Parkin,658,France,Male,32,8,0.00,1,1,1,80410.68,0
3568,3569,15672970,Chigolum,714,Spain,Male,20,3,0.00,2,0,1,150465.93,0
9278,9279,15584580,Fyodorova,443,France,Male,35,6,161111.45,1,0,0,13946.66,0
5909,5910,15713043,Siciliani,691,France,Female,33,6,0.00,2,1,1,100408.31,0
8996,8997,15578156,Anenechukwu,615,Spain,Male,32,5,138521.83,1,1,1,56897.10,0

5. Find the shape of the dataset.
o How many rows are there?
o How many columns are there?

In [9]:
df.shape[0]
df.shape[1]

14

6. Display complete information about the dataset using one method.
o Number of non-null values
o Data types
o Memory usage

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

7. Print the names of all columns in the dataset.

In [10]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

8. Find the data type of every column.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

9. Check for missing values in every column using:
o isnull().sum()
o isna().sum()

In [27]:
print(df.isnull().sum())
df=df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

10.Select only one column:
o CreditScore

In [20]:
df['CreditScore']

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

11.Select the following multiple columns:
o CustomerId
o Surname
o Balance
o Exited

In [22]:
df[["CustomerId", "Surname", "Balance", "Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

12.Display only numeric columns using select_dtypes().

In [24]:
df.select_dtypes(include=['number'])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

13.Generate the statistical summary of all numeric columns using describe().

In [25]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

14.Check for duplicate rows in the dataset.
    o How many duplicate rows exist?
    o Remove all duplicate rows.

In [26]:
print(df.duplicated().sum())
df=df.drop_duplicates()

0

15.Count the number of customers in each class of the Exited column using
value_counts().

In [28]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Varshini\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [29]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

#Operators+Loops

1. Take two numbers from user. Perform all arithmetic operations and also check
which number is greater using comparison operators.

In [31]:
a=int(input("Enter first number"))
b=int(input("Enter first number"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("FloorDivision:",a//b)
print("Modulus:",a%b)
if a>b:
    print("a is greater than b:",a)
elif b>a:
    print("b is greater than a",b)
else:
    print("Both are equal")

Enter first number 10
Enter first number 5

Addition: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
FloorDivision: 2
Modulus: 0
a is greater than b: 10

2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
completely when number 40 is reached using break.

In [34]:
for i in range(1,51):
    if i==40:
        break
    if i % 5 == 0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

3. Take numbers from user until they enter negative number. Calculate sum and
average using while loop.

In [35]:
total=0
count=0
while True:
    n=int(input("Enter number:"))
    if n<0:
        break
    total+=n
    count+=1
if count>0:
    avg=total/count
    print("Sum :", total)
    print("Average :",avg)
else:
    print("No Positive Number")

Enter number: 1
Enter number: 2
Enter number: 3
Enter number: 4
Enter number: 5
Enter number: -1

Sum : 15
Average : 3.0

4. Print the following pattern using nested loops:

*****
****
***
**
*

In [36]:
for i in range(5,0,-1):
    for j in range(i):
        print("*", end="")
    print()

*****
****
***
**
*

5. Find the factorial of a number using for loop and also using while loop.

In [37]:
#using for loop
n=int(input("Enter number:"))
fact=1
for i in range(1, n+1):
    fact=fact*i
print("Factorial=", fact)

Enter number: 5

Factorial= 120

In [39]:
#using while loop
n=int(input("Enter number:"))
fact=1
i=1
while i<=n:
    fact=fact*i
    i+=1
print("Factorial=", fact)

Enter number: 6

Factorial= 720

#DataTypes & Methods

In [41]:
s="Varshini"
print(s.upper())
print(s.count('a'))
print(s.replace("","-"))
if s.startswith("Hello"):
    print("String starts with Hello")
else:
    print("String does not start with Hello")

VARSHINI
1
-V-a-r-s-h-i-n-i-
String does not start with Hello

7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
and reverse.

In [46]:
list1=[1,2,3,4,5,6]
print(list1)
list1.append(8)
print(list1)
list1.insert(3,9)
print(list1)
list1.remove(5)
print(list1)
list1.pop()
print(list1)
list1.sort(reverse=True)
print(list1)
list1.reverse()
print(list1)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 8]
[1, 2, 3, 9, 4, 5, 6, 8]
[1, 2, 3, 9, 4, 6, 8]
[1, 2, 3, 9, 4, 6]
[9, 6, 4, 3, 2, 1]
[1, 2, 3, 4, 6, 9]

8. Create a dictionary of 4 students (name:marks). Print only those students who
scored more than 80 using items().

In [49]:
s={"varsh":80,"Akshii":85,"harii":90,"anu":99}
print("Students who scored more than 80")
for name,marks in s.items():
    if marks > 80:
        print(name, ":",marks)

Students who scored more than 80
Akshii : 85
harii : 90
anu : 99

9. Create two sets and perform union, intersection, difference. Also add and discard
elements.

In [52]:
s1={10,20,30,40}
s2={30,40,50,60}
print("set1:",s1)
print("set2:",s2)
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.difference(s2))
s1.add(60)
print(s1)
s1.discard(30)
print(s1)

set1: {40, 10, 20, 30}
set2: {40, 50, 60, 30}
{40, 10, 50, 20, 60, 30}
{40, 30}
{10, 20}
{40, 10, 20, 60, 30}
{40, 10, 20, 60}

#Oop+ encapsulation

10. Create a class Student with private attribute __marks. Add getter and setter with
validation (0–100).

In [53]:
class Student:
    def __init__(self, marks):
        self.__marks = 0
        self.set_marks(marks)
    def get_marks(self):
        return self.__marks

    def set_marks(self, marks):
        if 0 <= marks <= 100:
            self.__marks = marks
        else:
            print("Marks should be between 0 and 100.")

s = Student(85)
print("Marks:", s.get_marks())
s.set_marks(95)
print("Updated Marks:", s.get_marks())
s.set_marks(120)
print("Final Marks:", s.get_marks())

Marks: 85
Updated Marks: 95
Invalid marks! Marks should be between 0 and 100.
Final Marks: 95

11. Create class BankAccount with private __balance. Add deposit and withdraw
methods. Raise custom exception if balance becomes negative.

In [54]:
class InsufficientBalanceError(Exception):
    pass
class BankAccount:
    def __init__(self, balance):
        self.__balance = balance

    def deposit(self, amount):
        self.__balance += amount
        print("Deposited:", amount)
        print("Balance:", self.__balance)

    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise InsufficientBalanceError("Balance cannot be negative.")
        self.__balance -= amount
        print("Withdrawn:", amount)
        print("Balance:", self.__balance)

account = BankAccount(5000)
account.deposit(1000)
try:
    account.withdraw(2000)
    account.withdraw(5000)
except InsufficientBalanceError as e:
    print(e)

Deposited: 1000
Balance: 6000
Withdrawn: 2000
Balance: 4000
Balance cannot be negative.

12. Create class Employee with class attribute company_name. Show that it is
shared by all objects. Also update the class attribute.

In [56]:
class Employee:
    company_name = "Amazon"

    def __init__(self, name):
        self.name = name

emp1 = Employee("Varshini")
emp2 = Employee("anu")
print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)
Employee.company_name = "ABC"
print("\nAfter updating company_name:\n")
print(emp1.name, "works at", emp1.company_name)
print(emp2.name, "works at", emp2.company_name)

Varshini works at Amazon
anu works at Amazon

After updating company_name:

Varshini works at ABC
anu works at ABC

13. Create class Product with private __price. Add getter and setter. Setter should
not allow price less than 100.

In [57]:
class Product:
    def __init__(self, price):
        self.__price = 100
        self.set_price(price)

    def get_price(self):
        return self.__price

    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Price must be at least 100.")

p = Product(500)
print("Price:", p.get_price())
p.set_price(800)
print("Updated Price:", p.get_price())
p.set_price(50)
print("Final Price:", p.get_price())

Price: 500
Updated Price: 800
Price must be at least 100.
Final Price: 800

In [60]:
class Rectangle:
    def __init__(self, length, width):
        self.__length = length
        self.__width = width
    def area(self):
        return self.__length * self.__width

    def perimeter(self):
        return 2 * (self.__length + self.__width)
r = Rectangle(10, 5)
print(r.area())
print(r.perimeter())

50
30

#Inheritance+Abstraction+super()

15. Create single level inheritance: Person → Student. Use super() in constructor.

In [61]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
class Student(Person):
    def __init__(self, name, age, course):
        super().__init__(name, age)   # Call parent constructor
        self.course = course
    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Course:", self.course)
s = Student("Varshini", 20, "DS")
s.display()

Name: Varshini
Age: 20
Course: DS

16. Create multi-level inheritance: Person → Employee → Manager. Override a
method at each level.

In [62]:
class Person:
    def show(self):
        print("Person")
class Employee(Person):
    def show(self):
        print("Employee")
class Manager(Employee):
    def show(self):
        print("Manager")
m = Manager()
m.show()

Manager

17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
method.

In [63]:
class Animal:
    def sound(self):
        print("Animals make sounds")
class Dog(Animal):
    def sound(self):
        print("Dog barks")
class Cat(Animal):
    def sound(self):
        print("Cat meows")
d = Dog()
c = Cat()
d.sound()
c.sound()

Dog barks
Cat meows

18. Create abstract class Shape with abstract method area(). Implement it in Circle
and Square using super().

In [64]:
from abc import ABC, abstractmethod
class Shape(ABC):
    def __init__(self):
        print("Shape Constructor")
    @abstractmethod
    def area(self):
        pass
class Circle(Shape):
    def __init__(self, radius):
        super().__init__()   
        self.radius = radius
    def area(self):
        return 3.14 * self.radius * self.radius
class Square(Shape):
    def __init__(self, side):
        super().__init__()   
        self.side = side
    def area(self):
        return self.side * self.side
c = Circle(5)
s = Square(4)
print( c.area())
print(s.area())

Shape Constructor
Shape Constructor
78.5
16

19. Create multiple inheritance with two classes Father and Mother. Create child
class and resolve method conflict.

In [65]:
class Father:
    def show(self):
        print("Father")
class Mother:
    def show(self):
        print("Mother")
class Child(Father, Mother):
    def show(self):
        print("Method conflict resolved:")
        Father.show(self)      
        Mother.show(self)      

c = Child()
c.show()

Method conflict resolved:
Father
Mother

#Overloading + Exception + File Handling

20. Create a class Calculator that can add 2 or 3 numbers (method overloading
using *args).

In [66]:
class Calculator:
    def add(self, *args):
        if len(args) == 2:
            print(args[0] + args[1])
        elif len(args) == 3:
            print(args[0] + args[1] + args[2])
        else:
            print("Enter only 2 or 3 numbers.")
c = Calculator()
c.add(10, 20)
c.add(10, 20, 30)

30
60

21. Create class Point and overload + and > operators.

In [67]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self, other):
        return Point(self.x + other.x, self.y + other.y)
    def __gt__(self, other):
        return (self.x + self.y) > (other.x + other.y)
    def display(self):
        print("Point(", self.x, ",", self.y, ")")
p1 = Point(2, 3)
p2 = Point(4, 5)
p3 = p1 + p2
print("After Addition:")
p3.display()
if p1 > p2:
    print("p1 is greater than p2")
else:
    print("p2 is greater than or equal to p1")

After Addition:
Point( 6 , 8 )
p2 is greater than or equal to p1

22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
multiple except blocks.

In [68]:
try:
    n1 = int(input("Enter number: "))
    n2 = int(input("Enter number: "))
    result = n1 / n2
    print("Result =", result)
    num = [10, 20, 30]
    index = int(input("Enter index (0-2): "))
    print("Element =", num[index])
except ValueError as e:
    print(e)
except ZeroDivisionError as e:
    print(e)
except IndexError as e:
    print(e)

Enter number:  2
Enter number:  5

Result = 0.4

Enter index (0-2):  1

Element = 20

23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

In [69]:
class InvalidAgeError(Exception):
    pass
try:
    age = int(input())
    if age < 18:
        raise InvalidAgeError("Age must be 18")
    print("Eligible")
except InvalidAgeError as e:
    print(e)

 20

Eligible

24. Write a program to read a file, count number of words, and write the count into
another file.

In [70]:
file = open("input.txt", "r")
data = file.read()
file.close()
word_count = len(data.split())
output = open("output.txt", "w")
output.write("Number of words: " + str(word_count))
output.close()
print("Word count written to output.txt")

Word count written to output.txt

25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
Handle FileNotFoundError.

In [71]:
while True:
    print("\n1. Write")
    print("2. Read")
    print("3. Append")
    print("4. Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        file = open("data.txt", "w")
        text = input("Enter text: ")
        file.write(text)
        file.close()
        print("written successfully.")
    elif choice == "2":
        try:
            file = open("data.txt", "r")
            print("\nFile Content:")
            print(file.read())
            file.close()
        except FileNotFoundError:
            print("File not found.")
    elif choice == "3":
        file = open("data.txt", "a")
        text = input("Enter text to append: ")
        file.write("\n" + text)
        file.close()
        print("Added successfully.")
    elif choice == "4":
        print("Exit")
        break
    else:
        print("Invalid choice")

1. Write
2. Read
3. Append
4. Exit

Enter your choice:  3
Enter text to append:  python

Added successfully.

1. Write
2. Read
3. Append
4. Exit

Enter your choice:  4

Exit